# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 990)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        MainWindow.setFont(font)
        MainWindow.setFocusPolicy(QtCore.Qt.TabFocus)
        MainWindow.setToolTipDuration(0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 140, 271, 400))
        self.groupBox_2.setObjectName("groupBox_2")
        self.test_button_0 = QtWidgets.QPushButton(self.groupBox_2)
        self.test_button_0.setGeometry(QtCore.QRect(170, 20, 90, 31))
        self.test_button_0.setObjectName("test_button_0")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 60, 54, 31))
        self.label_7.setObjectName("label_7")
        self.group_0 = QtWidgets.QGroupBox(self.groupBox_2)
        self.group_0.setGeometry(QtCore.QRect(10, 330, 251, 51))
        self.group_0.setObjectName("group_0")
        self.progressBar_0_0 = QtWidgets.QProgressBar(self.group_0)
        self.progressBar_0_0.setGeometry(QtCore.QRect(10, 20, 231, 23))
        self.progressBar_0_0.setProperty("value", 100)
        self.progressBar_0_0.setObjectName("progressBar_0_0")
        self.qcode_0 = QtWidgets.QLineEdit(self.groupBox_2)
        self.qcode_0.setGeometry(QtCore.QRect(50, 60, 211, 31))
        self.qcode_0.setTabletTracking(False)
        self.qcode_0.setMaxLength(12)
        self.qcode_0.setObjectName("qcode_0")
        self.label_res_0 = QtWidgets.QLabel(self.groupBox_2)
        self.label_res_0.setGeometry(QtCore.QRect(10, 25, 151, 21))
        self.label_res_0.setObjectName("label_res_0")
        self.textBrowser_0_0 = QtWidgets.QTextBrowser(self.groupBox_2)
        self.textBrowser_0_0.setGeometry(QtCore.QRect(10, 100, 251, 221))
        self.textBrowser_0_0.setObjectName("textBrowser_0_0")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(320, 140, 271, 400))
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_6.setGeometry(QtCore.QRect(290, 0, 271, 301))
        self.groupBox_6.setObjectName("groupBox_6")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_5.setGeometry(QtCore.QRect(180, 20, 75, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.listView_5 = QtWidgets.QListView(self.groupBox_6)
        self.listView_5.setGeometry(QtCore.QRect(10, 50, 251, 192))
        self.listView_5.setObjectName("listView_5")
        self.label_9 = QtWidgets.QLabel(self.groupBox_6)
        self.label_9.setGeometry(QtCore.QRect(10, 260, 54, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_6)
        self.label_10.setGeometry(QtCore.QRect(73, 260, 181, 21))
        self.label_10.setObjectName("label_10")
        self.group_1 = QtWidgets.QGroupBox(self.groupBox_3)
        self.group_1.setGeometry(QtCore.QRect(10, 330, 251, 51))
        self.group_1.setObjectName("group_1")
        self.progressBar_0_1 = QtWidgets.QProgressBar(self.group_1)
        self.progressBar_0_1.setGeometry(QtCore.QRect(10, 20, 241, 23))
        self.progressBar_0_1.setProperty("value", 24)
        self.progressBar_0_1.setObjectName("progressBar_0_1")
        self.test_button_1 = QtWidgets.QPushButton(self.groupBox_3)
        self.test_button_1.setGeometry(QtCore.QRect(170, 20, 90, 31))
        self.test_button_1.setObjectName("test_button_1")
        self.label_26 = QtWidgets.QLabel(self.groupBox_3)
        self.label_26.setGeometry(QtCore.QRect(10, 60, 54, 21))
        self.label_26.setObjectName("label_26")
        self.qcode_1 = QtWidgets.QLineEdit(self.groupBox_3)
        self.qcode_1.setGeometry(QtCore.QRect(50, 60, 211, 31))
        self.qcode_1.setMaxLength(12)
        self.qcode_1.setObjectName("qcode_1")
        self.label_res_1 = QtWidgets.QLabel(self.groupBox_3)
        self.label_res_1.setGeometry(QtCore.QRect(10, 20, 151, 31))
        self.label_res_1.setObjectName("label_res_1")
        self.textBrowser_0_1 = QtWidgets.QTextBrowser(self.groupBox_3)
        self.textBrowser_0_1.setGeometry(QtCore.QRect(10, 100, 251, 221))
        self.textBrowser_0_1.setObjectName("textBrowser_0_1")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(610, 140, 271, 400))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_28 = QtWidgets.QLabel(self.groupBox_4)
        self.label_28.setGeometry(QtCore.QRect(10, 60, 54, 21))
        self.label_28.setObjectName("label_28")
        self.group_2 = QtWidgets.QGroupBox(self.groupBox_4)
        self.group_2.setGeometry(QtCore.QRect(10, 330, 251, 51))
        self.group_2.setObjectName("group_2")
        self.progressBar_0_2 = QtWidgets.QProgressBar(self.group_2)
        self.progressBar_0_2.setGeometry(QtCore.QRect(10, 20, 241, 23))
        self.progressBar_0_2.setProperty("value", 24)
        self.progressBar_0_2.setObjectName("progressBar_0_2")
        self.test_button_2 = QtWidgets.QPushButton(self.groupBox_4)
        self.test_button_2.setGeometry(QtCore.QRect(170, 20, 90, 31))
        self.test_button_2.setObjectName("test_button_2")
        self.qcode_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.qcode_2.setGeometry(QtCore.QRect(50, 60, 211, 31))
        self.qcode_2.setMaxLength(12)
        self.qcode_2.setObjectName("qcode_2")
        self.label_res_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_res_2.setGeometry(QtCore.QRect(10, 20, 151, 31))
        self.label_res_2.setObjectName("label_res_2")
        self.textBrowser_0_2 = QtWidgets.QTextBrowser(self.groupBox_4)
        self.textBrowser_0_2.setGeometry(QtCore.QRect(10, 100, 251, 221))
        self.textBrowser_0_2.setObjectName("textBrowser_0_2")
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setGeometry(QtCore.QRect(900, 140, 271, 400))
        self.groupBox_7.setObjectName("groupBox_7")
        self.group_3 = QtWidgets.QGroupBox(self.groupBox_7)
        self.group_3.setGeometry(QtCore.QRect(10, 330, 251, 51))
        self.group_3.setObjectName("group_3")
        self.progressBar_0_3 = QtWidgets.QProgressBar(self.group_3)
        self.progressBar_0_3.setGeometry(QtCore.QRect(10, 20, 241, 23))
        self.progressBar_0_3.setProperty("value", 24)
        self.progressBar_0_3.setObjectName("progressBar_0_3")
        self.test_button_3 = QtWidgets.QPushButton(self.groupBox_7)
        self.test_button_3.setGeometry(QtCore.QRect(170, 20, 90, 31))
        self.test_button_3.setObjectName("test_button_3")
        self.label_12 = QtWidgets.QLabel(self.groupBox_7)
        self.label_12.setGeometry(QtCore.QRect(10, 60, 54, 21))
        self.label_12.setObjectName("label_12")
        self.qcode_3 = QtWidgets.QLineEdit(self.groupBox_7)
        self.qcode_3.setGeometry(QtCore.QRect(50, 60, 211, 31))
        self.qcode_3.setMaxLength(12)
        self.qcode_3.setObjectName("qcode_3")
        self.label_res_3 = QtWidgets.QLabel(self.groupBox_7)
        self.label_res_3.setGeometry(QtCore.QRect(10, 20, 151, 31))
        self.label_res_3.setObjectName("label_res_3")
        self.textBrowser_0_3 = QtWidgets.QTextBrowser(self.groupBox_7)
        self.textBrowser_0_3.setGeometry(QtCore.QRect(10, 100, 251, 221))
        self.textBrowser_0_3.setObjectName("textBrowser_0_3")
        self.groupBox_8 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_8.setGeometry(QtCore.QRect(1190, 140, 271, 400))
        self.groupBox_8.setObjectName("groupBox_8")
        self.group_4 = QtWidgets.QGroupBox(self.groupBox_8)
        self.group_4.setGeometry(QtCore.QRect(10, 330, 251, 51))
        self.group_4.setObjectName("group_4")
        self.progressBar_0_4 = QtWidgets.QProgressBar(self.group_4)
        self.progressBar_0_4.setGeometry(QtCore.QRect(10, 20, 241, 23))
        self.progressBar_0_4.setProperty("value", 24)
        self.progressBar_0_4.setObjectName("progressBar_0_4")
        self.test_button_4 = QtWidgets.QPushButton(self.groupBox_8)
        self.test_button_4.setGeometry(QtCore.QRect(170, 20, 90, 31))
        self.test_button_4.setObjectName("test_button_4")
        self.label_14 = QtWidgets.QLabel(self.groupBox_8)
        self.label_14.setGeometry(QtCore.QRect(10, 60, 54, 21))
        self.label_14.setObjectName("label_14")
        self.qcode_4 = QtWidgets.QLineEdit(self.groupBox_8)
        self.qcode_4.setGeometry(QtCore.QRect(50, 60, 211, 31))
        self.qcode_4.setMaxLength(12)
        self.qcode_4.setObjectName("qcode_4")
        self.label_res_4 = QtWidgets.QLabel(self.groupBox_8)
        self.label_res_4.setGeometry(QtCore.QRect(10, 20, 151, 31))
        self.label_res_4.setObjectName("label_res_4")
        self.textBrowser_0_4 = QtWidgets.QTextBrowser(self.groupBox_8)
        self.textBrowser_0_4.setGeometry(QtCore.QRect(10, 100, 251, 221))
        self.textBrowser_0_4.setObjectName("textBrowser_0_4")
        self.groupBox_14 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_14.setGeometry(QtCore.QRect(610, 550, 271, 400))
        self.groupBox_14.setObjectName("groupBox_14")
        self.label_54 = QtWidgets.QLabel(self.groupBox_14)
        self.label_54.setGeometry(QtCore.QRect(10, 70, 54, 21))
        self.label_54.setObjectName("label_54")
        self.test_button_7 = QtWidgets.QPushButton(self.groupBox_14)
        self.test_button_7.setGeometry(QtCore.QRect(170, 30, 90, 31))
        self.test_button_7.setObjectName("test_button_7")
        self.group_7 = QtWidgets.QGroupBox(self.groupBox_14)
        self.group_7.setGeometry(QtCore.QRect(10, 340, 251, 51))
        self.group_7.setObjectName("group_7")
        self.progressBar_0_7 = QtWidgets.QProgressBar(self.group_7)
        self.progressBar_0_7.setGeometry(QtCore.QRect(10, 20, 241, 23))
        self.progressBar_0_7.setProperty("value", 24)
        self.progressBar_0_7.setObjectName("progressBar_0_7")
        self.qcode_7 = QtWidgets.QLineEdit(self.groupBox_14)
        self.qcode_7.setGeometry(QtCore.QRect(50, 70, 211, 31))
        self.qcode_7.setMaxLength(12)
        self.qcode_7.setObjectName("qcode_7")
        self.label_res_7 = QtWidgets.QLabel(self.groupBox_14)
        self.label_res_7.setGeometry(QtCore.QRect(10, 30, 151, 31))
        self.label_res_7.setObjectName("label_res_7")
        self.textBrowser_0_7 = QtWidgets.QTextBrowser(self.groupBox_14)
        self.textBrowser_0_7.setGeometry(QtCore.QRect(10, 110, 251, 221))
        self.textBrowser_0_7.setObjectName("textBrowser_0_7")
        self.groupBox_9 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_9.setGeometry(QtCore.QRect(1190, 550, 271, 400))
        self.groupBox_9.setObjectName("groupBox_9")
        self.label_46 = QtWidgets.QLabel(self.groupBox_9)
        self.label_46.setGeometry(QtCore.QRect(10, 70, 54, 21))
        self.label_46.setObjectName("label_46")
        self.group_9 = QtWidgets.QGroupBox(self.groupBox_9)
        self.group_9.setGeometry(QtCore.QRect(10, 340, 251, 51))
        self.group_9.setObjectName("group_9")
        self.progressBar_0_9 = QtWidgets.QProgressBar(self.group_9)
        self.progressBar_0_9.setGeometry(QtCore.QRect(10, 20, 241, 23))
        self.progressBar_0_9.setProperty("value", 24)
        self.progressBar_0_9.setObjectName("progressBar_0_9")
        self.test_button_9 = QtWidgets.QPushButton(self.groupBox_9)
        self.test_button_9.setGeometry(QtCore.QRect(170, 30, 90, 31))
        self.test_button_9.setObjectName("test_button_9")
        self.qcode_9 = QtWidgets.QLineEdit(self.groupBox_9)
        self.qcode_9.setGeometry(QtCore.QRect(50, 70, 211, 31))
        self.qcode_9.setMaxLength(12)
        self.qcode_9.setObjectName("qcode_9")
        self.label_res_9 = QtWidgets.QLabel(self.groupBox_9)
        self.label_res_9.setGeometry(QtCore.QRect(10, 30, 151, 31))
        self.label_res_9.setObjectName("label_res_9")
        self.textBrowser_0_9 = QtWidgets.QTextBrowser(self.groupBox_9)
        self.textBrowser_0_9.setGeometry(QtCore.QRect(10, 110, 251, 221))
        self.textBrowser_0_9.setObjectName("textBrowser_0_9")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(30, 550, 271, 400))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_30 = QtWidgets.QLabel(self.groupBox_5)
        self.label_30.setGeometry(QtCore.QRect(10, 70, 54, 21))
        self.label_30.setObjectName("label_30")
        self.test_button_5 = QtWidgets.QPushButton(self.groupBox_5)
        self.test_button_5.setGeometry(QtCore.QRect(170, 30, 90, 31))
        self.test_button_5.setObjectName("test_button_5")
        self.group_5 = QtWidgets.QGroupBox(self.groupBox_5)
        self.group_5.setGeometry(QtCore.QRect(10, 340, 251, 51))
        self.group_5.setObjectName("group_5")
        self.progressBar_0_5 = QtWidgets.QProgressBar(self.group_5)
        self.progressBar_0_5.setGeometry(QtCore.QRect(10, 20, 241, 23))
        self.progressBar_0_5.setProperty("value", 24)
        self.progressBar_0_5.setObjectName("progressBar_0_5")
        self.qcode_5 = QtWidgets.QLineEdit(self.groupBox_5)
        self.qcode_5.setGeometry(QtCore.QRect(50, 70, 211, 31))
        self.qcode_5.setMaxLength(12)
        self.qcode_5.setObjectName("qcode_5")
        self.label_res_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_res_5.setGeometry(QtCore.QRect(10, 30, 151, 31))
        self.label_res_5.setObjectName("label_res_5")
        self.textBrowser_0_5 = QtWidgets.QTextBrowser(self.groupBox_5)
        self.textBrowser_0_5.setGeometry(QtCore.QRect(10, 110, 251, 221))
        self.textBrowser_0_5.setObjectName("textBrowser_0_5")
        self.groupBox_11 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_11.setGeometry(QtCore.QRect(320, 550, 271, 400))
        self.groupBox_11.setObjectName("groupBox_11")
        self.groupBox_13 = QtWidgets.QGroupBox(self.groupBox_11)
        self.groupBox_13.setGeometry(QtCore.QRect(290, 0, 271, 301))
        self.groupBox_13.setObjectName("groupBox_13")
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox_13)
        self.pushButton_17.setGeometry(QtCore.QRect(180, 20, 75, 23))
        self.pushButton_17.setObjectName("pushButton_17")
        self.listView_17 = QtWidgets.QListView(self.groupBox_13)
        self.listView_17.setGeometry(QtCore.QRect(10, 50, 251, 192))
        self.listView_17.setObjectName("listView_17")
        self.label_59 = QtWidgets.QLabel(self.groupBox_13)
        self.label_59.setGeometry(QtCore.QRect(10, 260, 54, 21))
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(self.groupBox_13)
        self.label_60.setGeometry(QtCore.QRect(73, 260, 181, 21))
        self.label_60.setObjectName("label_60")
        self.label_32 = QtWidgets.QLabel(self.groupBox_11)
        self.label_32.setGeometry(QtCore.QRect(10, 70, 54, 21))
        self.label_32.setObjectName("label_32")
        self.group_6 = QtWidgets.QGroupBox(self.groupBox_11)
        self.group_6.setGeometry(QtCore.QRect(10, 340, 251, 51))
        self.group_6.setObjectName("group_6")
        self.progressBar_0_6 = QtWidgets.QProgressBar(self.group_6)
        self.progressBar_0_6.setGeometry(QtCore.QRect(10, 20, 241, 23))
        self.progressBar_0_6.setProperty("value", 24)
        self.progressBar_0_6.setObjectName("progressBar_0_6")
        self.test_button_6 = QtWidgets.QPushButton(self.groupBox_11)
        self.test_button_6.setGeometry(QtCore.QRect(170, 30, 90, 31))
        self.test_button_6.setObjectName("test_button_6")
        self.qcode_6 = QtWidgets.QLineEdit(self.groupBox_11)
        self.qcode_6.setGeometry(QtCore.QRect(50, 70, 211, 31))
        self.qcode_6.setMaxLength(12)
        self.qcode_6.setObjectName("qcode_6")
        self.label_res_6 = QtWidgets.QLabel(self.groupBox_11)
        self.label_res_6.setGeometry(QtCore.QRect(10, 30, 151, 31))
        self.label_res_6.setObjectName("label_res_6")
        self.textBrowser_0_6 = QtWidgets.QTextBrowser(self.groupBox_11)
        self.textBrowser_0_6.setGeometry(QtCore.QRect(10, 110, 251, 221))
        self.textBrowser_0_6.setObjectName("textBrowser_0_6")
        self.groupBox_10 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_10.setGeometry(QtCore.QRect(900, 550, 271, 400))
        self.groupBox_10.setObjectName("groupBox_10")
        self.group_8 = QtWidgets.QGroupBox(self.groupBox_10)
        self.group_8.setGeometry(QtCore.QRect(10, 340, 251, 51))
        self.group_8.setObjectName("group_8")
        self.progressBar_0_8 = QtWidgets.QProgressBar(self.group_8)
        self.progressBar_0_8.setGeometry(QtCore.QRect(10, 20, 241, 23))
        self.progressBar_0_8.setProperty("value", 24)
        self.progressBar_0_8.setObjectName("progressBar_0_8")
        self.test_button_8 = QtWidgets.QPushButton(self.groupBox_10)
        self.test_button_8.setGeometry(QtCore.QRect(170, 30, 90, 31))
        self.test_button_8.setObjectName("test_button_8")
        self.label_50 = QtWidgets.QLabel(self.groupBox_10)
        self.label_50.setGeometry(QtCore.QRect(10, 70, 54, 21))
        self.label_50.setObjectName("label_50")
        self.qcode_8 = QtWidgets.QLineEdit(self.groupBox_10)
        self.qcode_8.setGeometry(QtCore.QRect(50, 70, 211, 31))
        self.qcode_8.setMaxLength(12)
        self.qcode_8.setObjectName("qcode_8")
        self.label_res_8 = QtWidgets.QLabel(self.groupBox_10)
        self.label_res_8.setGeometry(QtCore.QRect(10, 30, 151, 31))
        self.label_res_8.setObjectName("label_res_8")
        self.textBrowser_0_8 = QtWidgets.QTextBrowser(self.groupBox_10)
        self.textBrowser_0_8.setGeometry(QtCore.QRect(10, 110, 251, 221))
        self.textBrowser_0_8.setObjectName("textBrowser_0_8")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(1480, 30, 411, 391))
        self.groupBox.setObjectName("groupBox")
        self.label_67 = QtWidgets.QLabel(self.groupBox)
        self.label_67.setGeometry(QtCore.QRect(30, 40, 71, 31))
        self.label_67.setObjectName("label_67")
        self.config_0 = QtWidgets.QLineEdit(self.groupBox)
        self.config_0.setGeometry(QtCore.QRect(100, 39, 281, 31))
        self.config_0.setObjectName("config_0")
        self.pushButton_19 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_19.setGeometry(QtCore.QRect(320, 340, 75, 31))
        self.pushButton_19.setObjectName("pushButton_19")
        self.groupBox_17 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_17.setGeometry(QtCore.QRect(20, 140, 371, 181))
        self.groupBox_17.setObjectName("groupBox_17")
        self.toption_0 = QtWidgets.QCheckBox(self.groupBox_17)
        self.toption_0.setGeometry(QtCore.QRect(40, 30, 91, 31))
        self.toption_0.setObjectName("toption_0")
        self.toption_1 = QtWidgets.QCheckBox(self.groupBox_17)
        self.toption_1.setGeometry(QtCore.QRect(150, 30, 101, 31))
        self.toption_1.setObjectName("toption_1")
        self.toption_2 = QtWidgets.QCheckBox(self.groupBox_17)
        self.toption_2.setGeometry(QtCore.QRect(260, 30, 91, 31))
        self.toption_2.setObjectName("toption_2")
        self.toption_3 = QtWidgets.QCheckBox(self.groupBox_17)
        self.toption_3.setGeometry(QtCore.QRect(40, 70, 91, 31))
        self.toption_3.setObjectName("toption_3")
        self.toption_4 = QtWidgets.QCheckBox(self.groupBox_17)
        self.toption_4.setGeometry(QtCore.QRect(150, 70, 91, 31))
        self.toption_4.setObjectName("toption_4")
        self.toption_5 = QtWidgets.QCheckBox(self.groupBox_17)
        self.toption_5.setGeometry(QtCore.QRect(260, 70, 91, 31))
        self.toption_5.setObjectName("toption_5")
        self.toption_6 = QtWidgets.QCheckBox(self.groupBox_17)
        self.toption_6.setGeometry(QtCore.QRect(40, 110, 91, 31))
        self.toption_6.setObjectName("toption_6")
        self.toption_7 = QtWidgets.QCheckBox(self.groupBox_17)
        self.toption_7.setGeometry(QtCore.QRect(150, 110, 91, 31))
        self.toption_7.setObjectName("toption_7")
        self.pushButton_20 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_20.setGeometry(QtCore.QRect(240, 340, 75, 31))
        self.pushButton_20.setObjectName("pushButton_20")
        self.checkBox_option_1 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_option_1.setGeometry(QtCore.QRect(230, 90, 111, 31))
        self.checkBox_option_1.setObjectName("checkBox_option_1")
        self.checkBox_option_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_option_2.setGeometry(QtCore.QRect(320, 90, 111, 31))
        self.checkBox_option_2.setObjectName("checkBox_option_2")
        self.groupBox_15 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_15.setGeometry(QtCore.QRect(1480, 430, 411, 521))
        self.groupBox_15.setObjectName("groupBox_15")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_15)
        self.textBrowser.setGeometry(QtCore.QRect(10, 20, 391, 491))
        self.textBrowser.setObjectName("textBrowser")
        self.groupBox_12 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_12.setGeometry(QtCore.QRect(30, 29, 1431, 91))
        self.groupBox_12.setObjectName("groupBox_12")
        self.label = QtWidgets.QLabel(self.groupBox_12)
        self.label.setGeometry(QtCore.QRect(50, 30, 54, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_12)
        self.label_2.setGeometry(QtCore.QRect(110, 30, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_12)
        self.label_3.setGeometry(QtCore.QRect(200, 30, 54, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:#32CD32")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_12)
        self.label_4.setGeometry(QtCore.QRect(250, 30, 54, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_12)
        self.label_5.setGeometry(QtCore.QRect(330, 30, 54, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:#FF0000")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_12)
        self.label_6.setGeometry(QtCore.QRect(370, 30, 54, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.groupBox_16 = QtWidgets.QGroupBox(self.groupBox_12)
        self.groupBox_16.setGeometry(QtCore.QRect(800, 10, 611, 71))
        self.groupBox_16.setObjectName("groupBox_16")
        self.bin_lab = QtWidgets.QLabel(self.groupBox_16)
        self.bin_lab.setGeometry(QtCore.QRect(20, 30, 411, 21))
        self.bin_lab.setObjectName("bin_lab")
        self.bin_button = QtWidgets.QPushButton(self.groupBox_16)
        self.bin_button.setGeometry(QtCore.QRect(500, 22, 75, 31))
        self.bin_button.setObjectName("bin_button")
        # MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        # MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.qcode_0, self.qcode_1)
        MainWindow.setTabOrder(self.qcode_1, self.qcode_2)
        MainWindow.setTabOrder(self.qcode_2, self.qcode_3)
        MainWindow.setTabOrder(self.qcode_3, self.qcode_4)
        MainWindow.setTabOrder(self.qcode_4, self.qcode_5)
        MainWindow.setTabOrder(self.qcode_5, self.qcode_6)
        MainWindow.setTabOrder(self.qcode_6, self.qcode_7)
        MainWindow.setTabOrder(self.qcode_7, self.qcode_8)
        MainWindow.setTabOrder(self.qcode_8, self.qcode_9)
        MainWindow.setTabOrder(self.qcode_9, self.textBrowser_0_2)
        MainWindow.setTabOrder(self.textBrowser_0_2, self.test_button_3)
        MainWindow.setTabOrder(self.test_button_3, self.pushButton_5)
        MainWindow.setTabOrder(self.pushButton_5, self.textBrowser_0_3)
        MainWindow.setTabOrder(self.textBrowser_0_3, self.test_button_4)
        MainWindow.setTabOrder(self.test_button_4, self.listView_5)
        MainWindow.setTabOrder(self.listView_5, self.textBrowser_0_4)
        MainWindow.setTabOrder(self.textBrowser_0_4, self.test_button_7)
        MainWindow.setTabOrder(self.test_button_7, self.textBrowser_0_1)
        MainWindow.setTabOrder(self.textBrowser_0_1, self.textBrowser_0_7)
        MainWindow.setTabOrder(self.textBrowser_0_7, self.test_button_9)
        MainWindow.setTabOrder(self.test_button_9, self.textBrowser_0_0)
        MainWindow.setTabOrder(self.textBrowser_0_0, self.textBrowser_0_9)
        MainWindow.setTabOrder(self.textBrowser_0_9, self.test_button_5)
        MainWindow.setTabOrder(self.test_button_5, self.test_button_1)
        MainWindow.setTabOrder(self.test_button_1, self.textBrowser_0_5)
        MainWindow.setTabOrder(self.textBrowser_0_5, self.pushButton_17)
        MainWindow.setTabOrder(self.pushButton_17, self.listView_17)
        MainWindow.setTabOrder(self.listView_17, self.test_button_6)
        MainWindow.setTabOrder(self.test_button_6, self.test_button_0)
        MainWindow.setTabOrder(self.test_button_0, self.textBrowser_0_6)
        MainWindow.setTabOrder(self.textBrowser_0_6, self.test_button_8)
        MainWindow.setTabOrder(self.test_button_8, self.test_button_2)
        MainWindow.setTabOrder(self.test_button_2, self.textBrowser_0_8)
        MainWindow.setTabOrder(self.textBrowser_0_8, self.config_0)
        MainWindow.setTabOrder(self.config_0, self.pushButton_19)
        MainWindow.setTabOrder(self.pushButton_19, self.toption_0)
        MainWindow.setTabOrder(self.toption_0, self.toption_1)
        MainWindow.setTabOrder(self.toption_1, self.toption_2)
        MainWindow.setTabOrder(self.toption_2, self.toption_3)
        MainWindow.setTabOrder(self.toption_3, self.toption_4)
        MainWindow.setTabOrder(self.toption_4, self.toption_5)
        MainWindow.setTabOrder(self.toption_5, self.toption_6)
        MainWindow.setTabOrder(self.toption_6, self.toption_7)
        MainWindow.setTabOrder(self.toption_7, self.pushButton_20)
        MainWindow.setTabOrder(self.pushButton_20, self.checkBox_option_1)
        MainWindow.setTabOrder(self.checkBox_option_1, self.checkBox_option_2)
        MainWindow.setTabOrder(self.checkBox_option_2, self.textBrowser)
        MainWindow.setTabOrder(self.textBrowser, self.bin_button)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "1#"))
        self.test_button_0.setText(_translate("MainWindow", "开启检测"))
        self.label_7.setText(_translate("MainWindow", "条码："))
        self.group_0.setTitle(_translate("MainWindow", "文件传输"))
        self.label_res_0.setText(_translate("MainWindow", "串口COM1打开成功"))
        self.groupBox_3.setTitle(_translate("MainWindow", "2#"))
        self.groupBox_6.setTitle(_translate("MainWindow", "1#"))
        self.pushButton_5.setText(_translate("MainWindow", "开启检测"))
        self.label_9.setText(_translate("MainWindow", "检测结果："))
        self.label_10.setText(_translate("MainWindow", "000000000000000"))
        self.group_1.setTitle(_translate("MainWindow", "文件传输"))
        self.test_button_1.setText(_translate("MainWindow", "开启检测"))
        self.label_26.setText(_translate("MainWindow", "条码："))
        self.label_res_1.setText(_translate("MainWindow", "串口COM1打开成功"))
        self.groupBox_4.setTitle(_translate("MainWindow", "3#"))
        self.label_28.setText(_translate("MainWindow", "条码："))
        self.group_2.setTitle(_translate("MainWindow", "文件传输"))
        self.test_button_2.setText(_translate("MainWindow", "开启检测"))
        self.label_res_2.setText(_translate("MainWindow", "串口COM1打开成功"))
        self.groupBox_7.setTitle(_translate("MainWindow", "4#"))
        self.group_3.setTitle(_translate("MainWindow", "文件传输"))
        self.test_button_3.setText(_translate("MainWindow", "开启检测"))
        self.label_12.setText(_translate("MainWindow", "条码："))
        self.label_res_3.setText(_translate("MainWindow", "串口COM1打开成功"))
        self.groupBox_8.setTitle(_translate("MainWindow", "5#"))
        self.group_4.setTitle(_translate("MainWindow", "文件传输"))
        self.test_button_4.setText(_translate("MainWindow", "开启检测"))
        self.label_14.setText(_translate("MainWindow", "条码："))
        self.label_res_4.setText(_translate("MainWindow", "串口COM1打开成功"))
        self.groupBox_14.setTitle(_translate("MainWindow", "8#"))
        self.label_54.setText(_translate("MainWindow", "条码："))
        self.test_button_7.setText(_translate("MainWindow", "开启检测"))
        self.group_7.setTitle(_translate("MainWindow", "文件传输"))
        self.label_res_7.setText(_translate("MainWindow", "串口COM1打开成功"))
        self.groupBox_9.setTitle(_translate("MainWindow", "10#"))
        self.label_46.setText(_translate("MainWindow", "条码："))
        self.group_9.setTitle(_translate("MainWindow", "文件传输"))
        self.test_button_9.setText(_translate("MainWindow", "开启检测"))
        self.label_res_9.setText(_translate("MainWindow", "串口COM1打开成功"))
        self.groupBox_5.setTitle(_translate("MainWindow", "6#"))
        self.label_30.setText(_translate("MainWindow", "条码："))
        self.test_button_5.setText(_translate("MainWindow", "开启检测"))
        self.group_5.setTitle(_translate("MainWindow", "文件传输"))
        self.label_res_5.setText(_translate("MainWindow", "串口COM1打开成功"))
        self.groupBox_11.setTitle(_translate("MainWindow", "7#"))
        self.groupBox_13.setTitle(_translate("MainWindow", "1#"))
        self.pushButton_17.setText(_translate("MainWindow", "开启检测"))
        self.label_59.setText(_translate("MainWindow", "检测结果："))
        self.label_60.setText(_translate("MainWindow", "000000000000000"))
        self.label_32.setText(_translate("MainWindow", "条码："))
        self.group_6.setTitle(_translate("MainWindow", "文件传输"))
        self.test_button_6.setText(_translate("MainWindow", "开启检测"))
        self.label_res_6.setText(_translate("MainWindow", "串口COM1打开成功"))
        self.groupBox_10.setTitle(_translate("MainWindow", "9#"))
        self.group_8.setTitle(_translate("MainWindow", "文件传输"))
        self.test_button_8.setText(_translate("MainWindow", "开启检测"))
        self.label_50.setText(_translate("MainWindow", "条码："))
        self.label_res_8.setText(_translate("MainWindow", "串口COM1打开成功"))
        self.groupBox.setTitle(_translate("MainWindow", "参数设置"))
        self.label_67.setText(_translate("MainWindow", "制令单号："))
        self.pushButton_19.setText(_translate("MainWindow", "保存设置"))
        self.groupBox_17.setTitle(_translate("MainWindow", "产测选项"))
        self.toption_0.setText(_translate("MainWindow", "版本号验证"))
        self.toption_1.setText(_translate("MainWindow", "PIN电压验证"))
        self.toption_2.setText(_translate("MainWindow", "通讯验证"))
        self.toption_3.setText(_translate("MainWindow", "频偏验证"))
        self.toption_4.setText(_translate("MainWindow", "过零验证"))
        self.toption_5.setText(_translate("MainWindow", "功耗验证"))
        self.toption_6.setText(_translate("MainWindow", "停电上报验证"))
        self.toption_7.setText(_translate("MainWindow", "读写ID验证"))
        self.pushButton_20.setText(_translate("MainWindow", "退出保存"))
        self.checkBox_option_1.setText(_translate("MainWindow", "烧录"))
        self.checkBox_option_2.setText(_translate("MainWindow", "产测"))
        self.groupBox_15.setTitle(_translate("MainWindow", "运行日志"))
        self.groupBox_12.setTitle(_translate("MainWindow", "文件/统计"))
        self.label.setText(_translate("MainWindow", "已检测："))
        self.label_2.setText(_translate("MainWindow", "123456"))
        self.label_3.setText(_translate("MainWindow", "PASS："))
        self.label_4.setText(_translate("MainWindow", "123455"))
        self.label_5.setText(_translate("MainWindow", "NG:"))
        self.label_6.setText(_translate("MainWindow", "1"))
        self.groupBox_16.setTitle(_translate("MainWindow", "bin文件"))
        self.bin_lab.setText(_translate("MainWindow", "TextLabel"))
        self.bin_button.setText(_translate("MainWindow", "选择文件"))
